FROM quay.io/yldio/alpine-node-containerpilot:latest
ARG NPM_TOKEN
ARG CIRCLE_BUILD_NUM
ENV NPM_TOKEN ${NPM_TOKEN}
ENV CIRCLE_BUILD_NUM ${CIRCLE_BUILD_NUM}
RUN echo -e "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
RUN make install compile
RUN npm version 1.0.0-${CIRCLE_BUILD_NUM}
RUN npm publish --access public
