FROM quay.io/yldio/alpine-node-containerpilot:latest
ARG NPM_TOKEN
ARG CIRCLE_BUILD_NUM
ENV NPM_TOKEN ${NPM_TOKEN}
ENV CIRCLE_BUILD_NUM ${CIRCLE_BUILD_NUM}
ENV VERSION 1.0.0

RUN echo -e "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
RUN make compile
RUN npm version --no-git-tag-version ${VERSION}-${CIRCLE_BUILD_NUM}
RUN npm publish --tag prerelease --access public
